sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 159357
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFBKMusZGnAUcrKge4J
    access-key-secret: jSNPlB0ZGY9plVINfVKNXWmPGniKZs
    bucket-name: zonghanbing